// Action types
export const PLACE_BOMBS = 'PLACE_BOMBS';
export const GENERATE_BOARD = 'GENERATE_BOARD';
export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY';
export const SET_REMAINING_TILES = 'SET_REMAINING_TILES';
export const MARK_TILE = 'MARK_TILE';
export const REVEAL_BOMBS = 'REVEAL_BOMBS';
